export type CatalogueStatus = 'active' | 'scraping' | 'coming_soon';
export type CatalogueGroup = 'arab_islamic_world' | 'ancient';

export const CATALOGUE_GROUPS = [
  {
    id: 'arab_islamic_world' as CatalogueGroup,
    labelAr: 'المنطقة العربية والإسلامية',
    labelEn: 'Arab & Islamic World',
    labelDe: 'Arabische & Islamische Welt',
    descAr:  'عملات العالم العربي والتراث الإسلامي عبر القارات',
    descEn:  'Coins of the Arab world and Islamic tradition across continents',
    descDe:  'Münzen der arabischen Welt und der islamischen Tradition über Kontinente',
  },
  {
    id: 'ancient' as CatalogueGroup,
    labelAr: 'الشرق الأدنى القديم',
    labelEn: 'Ancient Near East',
    labelDe: 'Alter Naher Osten',
    descAr:  'حضارات الشرق الأدنى القديم قبل الإسلام',
    descEn:  'Civilisations of the ancient Near East',
    descDe:  'Zivilisationen des alten Nahen Ostens',
  },
] as const;

export const CATALOGUES = [
  // ── Arab & Islamic World ────────────────────────────────────────────────
  {
    id: 'arab',
    slug: 'catalogue',
    group: 'arab_islamic_world' as CatalogueGroup,
    title: { ar: 'العملات العربية الحديثة', en: 'Modern Arab Coins', de: 'Moderne arabische Münzen' },
    subtitle: {
      ar: '5,505 عملة · 20 دولة · 1500–2026م',
      en: '5,505 coins · 20 countries · 1500–2026 CE',
      de: '5.505 Münzen · 20 Länder · 1500–2026 n. Chr.',
    },
    description: {
      ar: 'كتالوج شامل للعملات العربية الحديثة من 20 دولة عربية يمتد من العهد العثماني حتى اليوم',
      en: 'Comprehensive catalogue of modern Arab coins from 20 countries spanning the Ottoman era to present day',
      de: 'Umfassender Katalog moderner arabischer Münzen aus 20 Ländern vom Osmanischen Reich bis heute',
    },
    coinCount: 5505,
    ccFilter: { exclude: ['IS', 'SS'] },
    navPath: '/',
    status: 'active' as CatalogueStatus,
    seoKeywords: {
      en: ['Arab coins', 'Arabic coins', 'Arab numismatics', 'Egyptian coins', 'Saudi coins'],
      ar: ['عملات عربية', 'نقود عربية', 'كتالوج عملات', 'عملات مصرية', 'عملات سعودية'],
    },
  },
  {
    id: 'islamic',
    slug: 'islamic',
    group: 'arab_islamic_world' as CatalogueGroup,
    title: { ar: 'العملات الإسلامية', en: 'Islamic Dynastic Coins', de: 'Islamische Dynastiemünzen' },
    subtitle: {
      ar: '47,303 عملة · 18 سلالة · 41–922هـ',
      en: '47,303 coins · 18 dynasties · 41–922 AH',
      de: '47.303 Münzen · 18 Dynastien · 41–922 AH',
    },
    description: {
      ar: 'أكبر قاعدة بيانات للعملات الإسلامية على الإنترنت تشمل الأمويين والعباسيين والفاطميين والمماليك',
      en: 'The largest online Islamic coin database covering Umayyad, Abbasid, Fatimid, Ayyubid and Mamluk dynasties',
      de: 'Die größte Online-Datenbank islamischer Münzen: Umayyaden, Abbasiden, Fatimiden, Ayyubiden und Mamluken',
    },
    coinCount: 47303,
    ccFilter: { include: ['IS'] },
    navPath: '/islamic',
    status: 'active' as CatalogueStatus,
    seoKeywords: {
      en: ['Islamic coins', 'Umayyad coins', 'Abbasid coins', 'Fatimid coins', 'Mamluk coins'],
      ar: ['عملات إسلامية', 'دراهم أموية', 'دنانير عباسية', 'عملات فاطمية', 'عملات مملوكية'],
    },
  },
  {
    id: 'mughal',
    slug: 'mughal',
    group: 'arab_islamic_world' as CatalogueGroup,
    title: { ar: 'العملات المغولية', en: 'Mughal Empire', de: 'Mogulreich' },
    subtitle: {
      ar: '1526–1857م · الهند الإسلامية',
      en: '1526–1857 CE · Islamic India',
      de: '1526–1857 n.Chr. · Islamisches Indien',
    },
    description: {
      ar: 'عملات الإمبراطورية المغولية في الهند — من بابر إلى أورنكزيب. حملت نقوشاً عربية إسلامية',
      en: 'Coins of the Mughal Empire — from Babur to Aurangzeb, bearing Arabic Islamic inscriptions',
      de: 'Münzen des Mogulreichs — von Babur bis Aurangzeb, mit arabischen islamischen Inschriften',
    },
    navPath: '/mughal',
    ccFilter: { include: ['MG'] },
    status: 'scraping' as CatalogueStatus,
  },
  {
    id: 'delhi',
    slug: 'delhi',
    group: 'arab_islamic_world' as CatalogueGroup,
    title: { ar: 'سلطنة دلهي', en: 'Delhi Sultanate', de: 'Delhi-Sultanat' },
    subtitle: {
      ar: '1206–1526م · الهند الإسلامية',
      en: '1206–1526 CE · Islamic India',
      de: '1206–1526 n.Chr. · Islamisches Indien',
    },
    description: {
      ar: 'عملات سلطنة دلهي — الدول الإسلامية الأولى في شبه القارة الهندية 1206–1526م',
      en: 'Coins of the Delhi Sultanate — the early Islamic states of the Indian subcontinent 1206–1526 CE',
      de: 'Münzen des Delhi-Sultanats — die frühen islamischen Staaten des indischen Subkontinents 1206–1526 n.Chr.',
    },
    navPath: '/delhi',
    ccFilter: { include: ['DS'] },
    status: 'scraping' as CatalogueStatus,
  },

  {
    id: 'ottoman',
    slug: 'ottoman',
    group: 'arab_islamic_world' as CatalogueGroup,
    title: { ar: 'الدولة العثمانية', en: 'Ottoman Empire', de: 'Osmanisches Reich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات الدولة العثمانية العريقة التي حكمت على مدار ستة قرون',
      en: 'Coins of the Ottoman Empire, which ruled for six centuries across three continents',
      de: 'Münzen des Osmanischen Reichs, das sechs Jahrhunderte lang drei Kontinente regierte',
    },
    status: 'coming_soon' as CatalogueStatus,
  },

  // ── Ancient Middle East ─────────────────────────────────────────────────
  {
    id: 'sasanian',
    slug: 'sasanian',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات الساسانية', en: 'Sasanian Empire', de: 'Sassanidisches Reich' },
    subtitle: {
      ar: '7,995 عملة · 224–651م · فارس والعراق',
      en: '7,995 coins · 224–651 CE · Persia & Iraq',
      de: '7.995 Münzen · 224–651 n.Chr. · Persien & Irak',
    },
    description: {
      ar: 'العملات الساسانية — إمبراطورية فارس العظيمة التي حكمت من 224 إلى 651م',
      en: 'Sasanian coins — the Persian dynasty that ruled 224–651 CE, leaving an exceptional numismatic legacy',
      de: 'Sassanidische Münzen — die persische Dynastie, die 224–651 n.Chr. regierte',
    },
    coinCount: 7995,
    ccFilter: { include: ['SS'] },
    navPath: '/sasanian',
    status: 'active' as CatalogueStatus,
    seoKeywords: {
      en: ['Sasanian coins', 'Persian coins', 'Sassanid coins', 'ancient Persian numismatics'],
      ar: ['عملات ساسانية', 'عملات فارسية', 'نمسماتيا ساسانية'],
    },
  },
  {
    id: 'nabataean',
    slug: 'nabataean',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات النبطية', en: 'Nabataean Kingdom', de: 'Nabatäerreich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات مملكة الأنباط — الحضارة العربية القديمة في البتراء والجزيرة العربية',
      en: 'Coins of the Nabataean Kingdom — the ancient Arab civilisation centred at Petra',
      de: 'Münzen des Nabatäerreichs — die antike arabische Zivilisation mit Zentrum in Petra',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'byzantine',
    slug: 'byzantine',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات البيزنطية', en: 'Byzantine Empire', de: 'Byzantinisches Reich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'العملات البيزنطية — من القسطنطينية إلى الأراضي العربية',
      en: 'Byzantine coins — all issues across the Eastern Roman Empire and Arab lands',
      de: 'Byzantinische Münzen — alle Emissionen im Oströmischen Reich und in arabischen Gebieten',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'roman',
    slug: 'roman',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات الرومانية', en: 'Roman Empire', de: 'Römisches Reich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'العملات الرومانية المتعلقة بالشرق الأوسط وشمال أفريقيا',
      en: 'Roman coins relevant to the Middle East and North Africa',
      de: 'Römische Münzen mit Bezug zum Nahen Osten und Nordafrika',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'ptolemaic',
    slug: 'ptolemaic',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات البطلمية', en: 'Ptolemaic Kingdom', de: 'Ptolemäisches Reich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات المملكة البطلمية في مصر — من الإسكندر الأكبر حتى كليوباترا السابعة',
      en: 'Coins of the Ptolemaic Kingdom of Egypt — from Alexander the Great to Cleopatra VII',
      de: 'Münzen des ptolemäischen Königreichs Ägypten — von Alexander dem Großen bis Kleopatra VII',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'crusader',
    slug: 'crusader',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'عملات الحروب الصليبية', en: 'Crusader States', de: 'Kreuzfahrerstaaten' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات الممالك الصليبية في بلاد الشام وفلسطين والأراضي المقدسة',
      en: 'Coins of the Crusader states in the Levant, Palestine and the Holy Land',
      de: 'Münzen der Kreuzfahrerstaaten in der Levante, Palästina und dem Heiligen Land',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'achaemenid',
    slug: 'achaemenid',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'العملات الأخمينية', en: 'Achaemenid Persia', de: 'Achämenidisches Persien' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات الإمبراطورية الأخمينية الفارسية — من قورش الكبير حتى دارا الثالث',
      en: 'Coins of the Achaemenid Persian Empire — from Cyrus the Great to Darius III',
      de: 'Münzen des achämenidischen Perserreichs — von Kyros dem Großen bis Dareios III',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'parthian',
    slug: 'parthian',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'الإمبراطورية الفرثية', en: 'Parthian Empire', de: 'Partherreich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات الإمبراطورية الفرثية — الحضارة الإيرانية التي حكمت الشرق الأوسط قرونًا',
      en: 'Coins of the Parthian Empire — the Iranian dynasty that rivalled Rome for centuries',
      de: 'Münzen des Partherreichs — die iranische Dynastie, die Roms Rivale war',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'seleucid',
    slug: 'seleucid',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'الإمبراطورية السلوقية', en: 'Seleucid Empire', de: 'Seleukidenreich' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات الإمبراطورية السلوقية — خلفاء الإسكندر في الشرق',
      en: 'Coins of the Seleucid Empire — Alexander\'s successors in the East',
      de: 'Münzen des Seleukidenreichs — Alexanders Nachfolger im Osten',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
  {
    id: 'phoenician',
    slug: 'phoenician',
    group: 'ancient' as CatalogueGroup,
    title: { ar: 'المدن الفينيقية', en: 'Phoenician Cities', de: 'Phönizische Städte' },
    subtitle: { ar: 'قريباً', en: 'Coming soon', de: 'Demnächst' },
    description: {
      ar: 'عملات المدن الفينيقية — صور وصيدا وبيبلوس على ساحل لبنان',
      en: 'Coins of the Phoenician cities — Tyre, Sidon and Byblos on the Lebanese coast',
      de: 'Münzen der phönizischen Städte — Tyros, Sidon und Byblos an der libanesischen Küste',
    },
    status: 'coming_soon' as CatalogueStatus,
  },
] as const;
