import type { Coin } from '@/types/coin';
// ─── Translation dictionary (auto-generated from full coins.json scan) ─────────
const PHRASE_MAP: [RegExp, string][] = [
  [/Grand Egyptian Museum/gi,                    'المتحف المصري الكبير'],
  [/Khofo Solar Boat/gi,                         'مركب خوفو الشمسية'],
  [/Ramesses II Hanging Obelisk/gi,              'مسلة رمسيس الثاني المعلقة'],
  [/Ramesses II Statue/gi,                       'تمثال رمسيس الثاني'],
  [/Hatshepsut Statue/gi,                        'تمثال حتشبسوت'],
  [/Tut Gold Mask/gi,                            'قناع توت الذهبي'],
  [/Aswan High Dam/gi,                           'السد العالي بأسوان'],
  [/Cairo University/gi,                         'جامعة القاهرة'],
  [/Cairo Stadium/gi,                            'استاد القاهرة'],
  [/Alexandria University/gi,                    'جامعة الإسكندرية'],
  [/School of Agriculture/gi,                    'مدرسة الزراعة'],
  [/Egyptian Radio Broadcasting/gi,              'الإذاعة المصرية'],
  [/State Lawsuits/gi,                           'قضايا الدولة'],
  [/Saving for Development/gi,                   'الادخار للتنمية'],
  [/Abbas Al-Aqqad/gi,                           'عباس العقاد'],
  [/Taha Hussein/gi,                             'طه حسين'],
  [/Georgi Zidan/gi,                             'جرجي زيدان'],
  [/Naguib Mahfouz/gi,                           'نجيب محفوظ'],
  [/Bibliotheca Alexandrina/gi,                  'مكتبة الإسكندرية'],
  [/Anwar Sadat/gi,                              'أنور السادات'],
  [/Gamal Abdel Nasser/gi,                       'جمال عبد الناصر'],
  [/Om Kalthoum/gi,                              'أم كلثوم'],
  [/Talaat Harb/gi,                              'طلعت حرب'],
  [/Suez Canal/gi,                               'قناة السويس'],
  [/Abu Simbel/gi,                               'أبو سمبل'],
  [/\bPyramids\b/gi,                             'الأهرامات'],
  [/Opera House/gi,                              'دار الأوبرا'],
  [/Nile Barrage/gi,                             'قناطر النيل'],
  [/Dar-el-Eloum/gi,                             'دار العلوم'],
  [/Portland Cement/gi,                          'الأسمنت البورتلاندي'],
  [/Egyptian-Israeli/gi,                         'مصري-إسرائيلي'],
  [/Non-aligned/gi,                              'عدم الانحياز'],
  [/\bEgyptAir\b/gi,                             'مصر للطيران'],
  [/\bMoulay\b/gi,                               'مولاي'],
  [/\bSidi\b/gi,                                 'سيدي'],
  [/Moulay Yusuf/gi,                             'مولاي يوسف'],
  [/Moulay Hassan/gi,                            'مولاي الحسن'],
  [/Sidi Mohammed/gi,                            'سيدي محمد'],
  [/Sidi Muhammad/gi,                            'سيدي محمد'],
  [/al-Rahman/gi,                                'الرحمن'],
  [/al-Hasan/gi,                                 'الحسن'],
  [/al-Aziz/gi,                                  'العزيز'],
  [/al-Nasir/gi,                                 'الناصر'],
  [/al-Mahdi/gi,                                 'المهدي'],
  [/al-Yazid/gi,                                 'اليزيد'],
  [/al-Rashid/gi,                                'الرشيد'],
  [/al-Mansur/gi,                                'المنصور'],
  [/al-Ghalib/gi,                                'الغالب'],
  [/al-Fath/gi,                                  'الفتح'],
  [/al-Wathiq/gi,                                'الواثق'],
  [/al-Hafiz/gi,                                 'الحافظ'],
  [/al-Abbas/gi,                                 'العباس'],
  [/al-Husayn/gi,                                'الحسين'],
  [/al-Mutawakkil/gi,                            'المتوكل'],
  [/al-Malik/gi,                                 'الملك'],
  [/al-Kitaoua/gi,                               'القيطاوة'],
  [/al-Araish/gi,                                'العرائش'],
  [/al-Sheikh/gi,                                'الشيخ'],
  [/al-Saghir/gi,                                'الصغير'],
  [/al-Azhar/gi,                                 'الأزهر'],
  [/al-Shaykh/gi,                                'الشيخ'],
  [/al-Karim/gi,                                 'الكريم'],
  [/al-Hadi/gi,                                  'الهادي'],
  [/al-Hajj/gi,                                  'الحج'],
  [/al-Walid/gi,                                 'الوليد'],
  [/\bMarrakesh\b/gi,                            'مراكش'],
  [/\bMarrakech\b/gi,                            'مراكش'],
  [/\bTetuan\b/gi,                               'تطوان'],
  [/\bTetouan\b/gi,                              'تطوان'],
  [/\bSijilmasah\b/gi,                           'سجلماسة'],
  [/\bEssaouira\b/gi,                            'الصويرة'],
  [/\bTanger\b/gi,                               'طنجة'],
  [/\bFes\b/gi,                                  'فاس'],
  [/\bRabat\b/gi,                                'الرباط'],
  [/\bMiknas\b/gi,                               'مكناس'],
  [/\bMeknes\b/gi,                               'مكناس'],
  [/\bTaroudant\b/gi,                            'تارودانت'],
  [/\bTilimsan\b/gi,                             'تلمسان'],
  [/\bChellah\b/gi,                              'شالة'],
  [/Kasbah Udayas/gi,                            'قصبة الأوداية'],
  [/Moroccan-American/gi,                        'مغربي-أمريكي'],
  [/Hussein Kamel/gi,                            'حسين كامل'],
  [/Abdul Hamid/gi,                              'عبدالحميد'],
  [/Abdul Aziz/gi,                               'عبدالعزيز'],
  [/Abdul Mecid/gi,                              'عبدالمجيد'],
  [/Salim ibn Sulayman/gi,                       'سليم بن سليمان'],
  [/Said Pasha/gi,                               'سعيد باشا'],
  [/Ali Bey/gi,                                  'علي بك'],
  [/Muhammad Ali/gi,                             'محمد علي'],
  [/Mohammed Ali/gi,                             'محمد علي'],
  [/Isma\'il/gi,                                 'إسماعيل'],
  [/Abul-Hasan/gi,                               'أبو الحسن'],
  [/Abul-\'Abbas/gi,                             'أبو العباس'],
  [/al-Mu\'tasim/gi,                             'المعتصم'],
  [/bin Laden/gi,                                'بن لادن'],
  [/Ibn Saud/gi,                                 'ابن سعود'],
  [/\bHejaz\b/gi,                                'الحجاز'],
  [/\bNejd\b/gi,                                 'نجد'],
  [/\bMecca\b/gi,                                'مكة المكرمة'],
  [/\bMedina\b/gi,                               'المدينة المنورة'],
  [/\bHazrat\b/gi,                               'حضرة'],
  [/\bZayed\b/gi,                                'زايد'],
  [/\bKhalifa\b/gi,                              'خليفة'],
  [/\bHamad\b/gi,                                'حمد'],
  [/\bSabah\b/gi,                                'صباح'],
  [/\bFaisal\b/gi,                               'فيصل'],
  [/\bFahd\b/gi,                                 'فهد'],
  [/\bAbdullah\b/gi,                             'عبدالله'],
  [/\bAbdulaziz\b/gi,                            'عبدالعزيز'],
  [/\bAbdulmecid\b/gi,                           'عبدالمجيد'],
  [/\bAbdulhamid\b/gi,                           'عبدالحميد'],
  [/\bQaboos\b/gi,                               'قابوس'],
  [/\bHaitham\b/gi,                              'هيثم'],
  [/\bTaimur\b/gi,                               'تيمور'],
  [/\bSalman\b/gi,                               'سلمان'],
  [/\bMaktoum\b/gi,                              'مكتوم'],
  [/\bRashid\b/gi,                               'راشد'],
  [/\bSaqr\b/gi,                                 'صقر'],
  [/\bHamdan\b/gi,                               'حمدان'],
  [/\bMuscat\b/gi,                               'مسقط'],
  [/\bNizwa\b/gi,                                'نزوى'],
  [/\bSohar\b/gi,                                'صحار'],
  [/\bMatrah\b/gi,                               'مطرح'],
  [/\bMirbat\b/gi,                               'مرباط'],
  [/\bKhasab\b/gi,                               'خصب'],
  [/\bBuraimi\b/gi,                              'البريمي'],
  [/\bDhofar\b/gi,                               'ظفار'],
  [/\bBahla\b/gi,                                'بهلاء'],
  [/\bJabrin\b/gi,                               'جبرين'],
  [/Sana\'a/gi,                                  'صنعاء'],
  [/\bSanaa\b/gi,                                'صنعاء'],
  [/Sa\'dah/gi,                                  'صعدة'],
  [/\bZabid\b/gi,                                'زبيد'],
  [/\bBaghdad\b/gi,                              'بغداد'],
  [/\bBasra\b/gi,                                'البصرة'],
  [/\bMosul\b/gi,                                'الموصل'],
  [/\bBabylon\b/gi,                              'بابل'],
  [/\bSaddam\b/gi,                               'صدام'],
  [/\bHammurabi\b/gi,                            'حمورابي'],
  [/\bIshtar\b/gi,                               'عشتار'],
  [/al-Qadisiyyah/gi,                            'القادسية'],
  [/\bJerash\b/gi,                               'جرش'],
  [/\bPetra\b/gi,                                'البتراء'],
  [/\bAmman\b/gi,                                'عمان'],
  [/Jeita Grotto/gi,                             'كهف جعيتا'],
  [/Raouche Rock/gi,                             'صخرة الروشة'],
  [/Cedars of Lebanon/gi,                        'أرز لبنان'],
  [/\bBeirut\b/gi,                               'بيروت'],
  [/\bAUB\b/gi,                                  'الجامعة الأمريكية'],
  [/\bBourguiba\b/gi,                            'بورقيبة'],
  [/\bCarthage\b/gi,                             'قرطاج'],
  [/\bJugurtha\b/gi,                             'يوغرطة'],
  [/\bHannibal\b/gi,                             'هنيبعل'],
  [/\bKairouan\b/gi,                             'القيروان'],
  [/\bMonastir\b/gi,                             'المنستير'],
  [/\bSfax\b/gi,                                 'صفاقس'],
  [/\bSbeitla\b/gi,                              'سبيطلة'],
  [/\bMedenine\b/gi,                             'مدنين'],
  [/\bNabeul\b/gi,                               'نابل'],
  [/\bAlgiers\b/gi,                              'الجزائر'],
  [/\bAlger\b/gi,                                'الجزائر'],
  [/\bOran\b/gi,                                 'وهران'],
  [/\bConstantine\b/gi,                          'قسنطينة'],
  [/\bTlemcen\b/gi,                              'تلمسان'],
  [/\bBoumediene\b/gi,                           'بومدين'],
  [/\bBoumedien\b/gi,                            'بومدين'],
  [/\bAbdelkader\b/gi,                           'عبد القادر'],
  [/\bBenbadis\b/gi,                             'ابن باديس'],
  [/Hassiba Ben Bouali/gi,                       'حسيبة بن بوعلي'],
  [/\bDamascus\b/gi,                             'دمشق'],
  [/\bAleppo\b/gi,                               'حلب'],
  [/\bAssad\b/gi,                                'الأسد'],
  [/\bHafez\b/gi,                                'حافظ'],
  [/Ba\'ath/gi,                                  'البعث'],
  [/\bBosra\b/gi,                                'بصرى'],
  [/\bJerusalem\b/gi,                            'القدس'],
  [/\bBethlehem\b/gi,                            'بيت لحم'],
  [/\bPhilae\b/gi,                               'فيلة'],
  [/\bArish\b/gi,                                'العريش'],
  [/Corrective Revolution/gi,                    'الثورة التصحيحية'],
  [/October War/gi,                              'حرب أكتوبر'],
  [/\bFAO\b/gi,                                  'منظمة الأغذية والزراعة'],
  [/\bUNESCO\b/gi,                               'اليونسكو'],
  [/\bUNICEF\b/gi,                               'اليونيسف'],
  [/\bWWF\b/gi,                                  'صندوق الطبيعة العالمي'],
  [/\bOAU\b/gi,                                  'منظمة الوحدة الأفريقية'],
  [/\bGCC\b/gi,                                  'مجلس التعاون الخليجي'],
  [/\bFIFA\b/gi,                                 'الفيفا'],
  [/\bIPU\b/gi,                                  'الاتحاد البرلماني الدولي'],
  [/\bILO\b/gi,                                  'منظمة العمل الدولية'],
  [/\bIWY\b/gi,                                  'السنة الدولية للمرأة'],
  [/\bIYDP\b/gi,                                 'السنة الدولية للمعاقين'],
  [/\bIYC\b/gi,                                  'السنة الدولية للطفل'],
  [/\bWTO\b/gi,                                  'منظمة التجارة العالمية'],
  [/\bGATT\b/gi,                                 'الجات'],
  [/\bICPD\b/gi,                                 'مؤتمر السكان'],
  [/\bUAR\b/gi,                                  'الجمهورية العربية المتحدة'],
  [/\bGEM\b/gi,                                  'م.م.ك'],
  [/Facing Right/gi,                             'الزي الملكي'],
  [/Civic Attire/gi,                             'الزي الملكي'],
  [/Facing Left/gi,                              'زي التشريفة العسكرية'],
  [/Reverse Trial/gi,                            'نموذج معكوس'],
  [/Trial Strike/gi,                             'نسخة تجريبية'],
  [/Gold Pattern/gi,                             'نموذج ذهب'],
  [/Bronze Pattern/gi,                           'نموذج برونز'],
  [/Old Design/gi,                               'تصميم قديم'],
  [/Royal Wedding/gi,                            'الزواج الملكي'],
  [/French Occupation/gi,                        'الاحتلال الفرنسي'],
  [/British Occupation/gi,                       'الاحتلال البريطاني'],
  [/With Hole/gi,                                'مثقوب'],
  [/Without Hole/gi,                             'غير مثقوب'],
  [/With Flower/gi,                              'بالوردة'],
  [/Type 1/gi,                                   'نوع أول'],
  [/Type 2/gi,                                   'نوع ثاني'],
  [/Type 3/gi,                                   'نوع ثالث'],
  [/Type I/gi,                                   'نوع أول'],
  [/Type II/gi,                                  'نوع ثاني'],
  [/Type III/gi,                                 'نوع ثالث'],
  [/\bPiedfort\b/gi,                             'بيدفور'],
  [/\bEssai\b/gi,                                'نموذج'],
  [/\bPrueba\b/gi,                               'نموذج'],
  [/\bEssay\b/gi,                                'نموذج'],
  [/\bCountermarked\b/gi,                        'مضروب بختم إضافي'],
  [/\bCountermark\b/gi,                          'ختم إضافي'],
  [/\bUniface\b/gi,                              'وجه واحد'],
  [/\bMule\b/gi,                                 'قطعة خطأ'],
  [/\bRestrike\b/gi,                             'إعادة ضرب'],
  [/\bStandard\b/gi,                             'نمط قياسي'],
  [/\bPiedfort\b/gi,                             'بيدفور'],
  [/\bSpecimen\b/gi,                             'نموذج خاص'],
  [/\bProof\b/gi,                                'نسخة مرآة'],
  [/Gold Pounds/gi,                              'جنيه ذهب'],
  [/Gold Pound/gi,                               'جنيه ذهب'],
  [/Zeri Mahbub/gi,                              'زر محبوب'],
  [/Zari Mahbub/gi,                              'زر محبوب'],
  [/Coyrek Rumi/gi,                              'كويريك رومي'],
  [/\bPounds\b/gi,                               'جنيه'],
  [/\bPound\b/gi,                                'جنيه'],
  [/\bPiastres\b/gi,                             'قرش'],
  [/\bPiastre\b/gi,                              'قرش'],
  [/\bMilliemes\b/gi,                            'مليم'],
  [/\bMillieme\b/gi,                             'مليم'],
  [/\bMillimes\b/gi,                             'مليم'],
  [/\bMillime\b/gi,                              'مليم'],
  [/\bMillim\b/gi,                               'مليم'],
  [/\bMils\b/gi,                                 'مليم'],
  [/\bDinars\b/gi,                               'دينار'],
  [/\bDinar\b/gi,                                'دينار'],
  [/\bDirhams\b/gi,                              'درهم'],
  [/\bDirham\b/gi,                               'درهم'],
  [/\bDirhem\b/gi,                               'درهم'],
  [/\bCentimes\b/gi,                             'سنتيم'],
  [/\bCentime\b/gi,                              'سنتيم'],
  [/\bSantim\b/gi,                               'سنتيم'],
  [/\bSantima\b/gi,                              'سنتيم'],
  [/\bSantimat\b/gi,                             'سنتيم'],
  [/\bFrancs\b/gi,                               'فرنك'],
  [/\bFranc\b/gi,                                'فرنك'],
  [/\bFrancs\b/gi,                               'فرنك'],
  [/\bLivres\b/gi,                               'ليرة'],
  [/\bLivre\b/gi,                                'ليرة'],
  [/\bLira\b/gi,                                 'ليرة'],
  [/\bRiyal\b/gi,                                'ريال'],
  [/\bRiyals\b/gi,                               'ريال'],
  [/\bRial\b/gi,                                 'ريال'],
  [/\bRials\b/gi,                                'ريال'],
  [/\bFils\b/gi,                                 'فلس'],
  [/\bFil\b/gi,                                  'فلس'],
  [/\bFals\b/gi,                                 'فلس'],
  [/\bFalus\b/gi,                                'فلوس'],
  [/\bFulus\b/gi,                                'فلوس'],
  [/\bBaisa\b/gi,                                'بيسة'],
  [/\bBaiza\b/gi,                                'بيسة'],
  [/\bBaisas\b/gi,                               'بيسة'],
  [/\bMazuna\b/gi,                               'مازونة'],
  [/\bMazunas\b/gi,                              'مازونة'],
  [/\bMazunas\b/gi,                              'مازونة'],
  [/\bMazouna\b/gi,                              'مازونة'],
  [/\bFalus\b/gi,                                'فلوس'],
  [/\bKharub\b/gi,                               'خروب'],
  [/\bKharuba\b/gi,                              'خروبة'],
  [/\bNasri\b/gi,                                'ناصري'],
  [/\bBudju\b/gi,                                'بدجو'],
  [/\bGhirsh\b/gi,                               'غرش'],
  [/\bGirush\b/gi,                               'غرش'],
  [/\bQirush\b/gi,                               'قروش'],
  [/\bQirsh\b/gi,                                'قرش'],
  [/\bHarf\b/gi,                                 'حرف'],
  [/\bRupee\b/gi,                                'روبية'],
  [/\bAnna\b/gi,                                 'آنة'],
  [/\bSanah\b/gi,                                'سنة'],
  [/\bOuguiya\b/gi,                              'أوقية'],
  [/\bSultani\b/gi,                              'سلطاني'],
  [/\bMangir\b/gi,                               'مانجير'],
  [/\bManghir\b/gi,                              'مانجير'],
  [/\bMahbub\b/gi,                               'محبوب'],
  [/\bPara\b/gi,                                 'بارة'],
  [/\bJadid\b/gi,                                'جديد'],
  [/\bMedini\b/gi,                               'مديني'],
  [/\bMedin\b/gi,                                'مديني'],
  [/\bAkche\b/gi,                                'أقجة'],
  [/\bAkce\b/gi,                                 'أقجة'],
  [/\bAsper\b/gi,                                'أسبر'],
  [/\bBeslik\b/gi,                               'بشلك'],
  [/\bBeshlik\b/gi,                              'بشلك'],
  [/\bOnluk\b/gi,                                'أونلوك'],
  [/\bAltin\b/gi,                                'ألتون'],
  [/\bLarin\b/gi,                                'لارين'],
  [/\bKhumsiyyah\b/gi,                           'خمسية'],
  [/\bKhamsiya\b/gi,                             'خمسية'],
  [/\bKhamsiyya\b/gi,                            'خمسية'],
  [/\bKhumsi\b/gi,                               'خمسي'],
  [/\bBenduqi\b/gi,                              'بندقي'],
  [/\bMithqal\b/gi,                              'مثقال'],
  [/\bMithqals\b/gi,                             'مثقال'],
  [/\bAshrafi\b/gi,                              'أشرفي'],
  [/\bShahi\b/gi,                                'شاهي'],
  [/\bHalalah\b/gi,                              'هللة'],
  [/\bHalalas\b/gi,                              'هللة'],
  [/\bHalala\b/gi,                               'هللة'],
  [/\bHalal\b/gi,                                'هلال'],
  [/\bBuqsha\b/gi,                               'بقشة'],
  [/\bBuqshah\b/gi,                              'بقشة'],
  [/\bWabra\b/gi,                                'وبرة'],
  [/\bTaler\b/gi,                                'تالر'],
  [/\bThaler\b/gi,                               'تالر'],
  [/\bZolota\b/gi,                               'زلوطة'],
  [/\bGunayh\b/gi,                               'جنيه'],
  [/\bGirsh\b/gi,                                'غرش'],
  [/\bGhazi\b/gi,                                'غازي'],
  [/\bSaidi\b/gi,                                'سعيدي'],
  [/\bMahmudi\b/gi,                              'محمودي'],
  [/\bBenduqi\b/gi,                              'بندقي'],
  [/\bBaghlah\b/gi,                              'بغلة'],
  [/\bSanbuq\b/gi,                               'سنبوق'],
  [/\bBattil\b/gi,                               'بتيل'],
  [/\bGhanjah\b/gi,                              'غنجة'],
  [/\bMohammed\b/gi,                             'محمد'],
  [/\bMuhammad\b/gi,                             'محمد'],
  [/\bMuhammed\b/gi,                             'محمد'],
  [/\bMuhamed\b/gi,                              'محمد'],
  [/\bMohamed\b/gi,                              'محمد'],
  [/\bAhmad\b/gi,                                'أحمد'],
  [/\bAhmed\b/gi,                                'أحمد'],
  [/\bMahmud\b/gi,                               'محمود'],
  [/\bMustafa\b/gi,                              'مصطفى'],
  [/\bMehmed\b/gi,                               'محمد'],
  [/\bMehmet\b/gi,                               'محمد'],
  [/\bMurad\b/gi,                                'مراد'],
  [/\bSelim\b/gi,                                'سليم'],
  [/\bSalim\b/gi,                                'سليم'],
  [/\bSuleiman\b/gi,                             'سليمان'],
  [/\bSuleyman\b/gi,                             'سليمان'],
  [/\bSulayman\b/gi,                             'سليمان'],
  [/\bIbrahim\b/gi,                              'إبراهيم'],
  [/\bOsman\b/gi,                                'عثمان'],
  [/\bFuad\b/gi,                                 'فؤاد'],
  [/\bFarouk\b/gi,                               'فاروق'],
  [/\bFaruq\b/gi,                                'فاروق'],
  [/\bTewfik\b/gi,                               'توفيق'],
  [/\bIsmail\b/gi,                               'إسماعيل'],
  [/\bNasser\b/gi,                               'ناصر'],
  [/\bSadat\b/gi,                                'السادات'],
  [/\bMubarak\b/gi,                              'مبارك'],
  [/\bHusayn\b/gi,                               'حسين'],
  [/\bHussein\b/gi,                              'حسين'],
  [/\bHassan\b/gi,                               'الحسن'],
  [/\bYahya\b/gi,                                'يحيى'],
  [/\bYusuf\b/gi,                                'يوسف'],
  [/\bYousif\b/gi,                               'يوسف'],
  [/\bIdris\b/gi,                                'إدريس'],
  [/\bNaguib\b/gi,                               'نجيب'],
  [/\bGamal\b/gi,                                'جمال'],
  [/\bAnwar\b/gi,                                'أنور'],
  [/\bAbdel\b/gi,                                'عبد'],
  [/\bKhalid\b/gi,                               'خالد'],
  [/\bSaleh\b/gi,                                'صالح'],
  [/\bHamud\b/gi,                                'حمود'],
  [/\bFaris\b/gi,                                'فارس'],
  [/\bMarwan\b/gi,                               'مروان'],
  [/\bHisham\b/gi,                               'هشام'],
  [/\bIsa\b/gi,                                  'عيسى'],
  [/\bPhilip\b/gi,                               'فيليب'],
  [/\bTaha\b/gi,                                 'طه'],
  [/\bSusanne\b/gi,                              'سوزان'],
  [/\bZidan\b/gi,                                'زيدان'],
  [/\bGeorgi\b/gi,                               'جرجي'],
  [/\bAbbas\b/gi,                                'عباس'],
  [/\bAqqad\b/gi,                                'العقاد'],
  [/\bMaalouf\b/gi,                              'معلوف'],
  [/\bAmin\b/gi,                                 'أمين'],
  [/\bTalaat\b/gi,                               'طلعت'],
  [/\bHarb\b/gi,                                 'حرب'],
  [/\bShawki\b/gi,                               'شوقي'],
  [/\bRamses\b/gi,                               'رمسيس'],
  [/\bRamesses\b/gi,                             'رمسيس'],
  [/\bHatshepsut\b/gi,                           'حتشبسوت'],
  [/\bTutankhamun\b/gi,                          'توت عنخ آمون'],
  [/\bTutankhamen\b/gi,                          'توت عنخ آمون'],
  [/\bTut\b/gi,                                  'توت عنخ آمون'],
  [/\bNefertiti\b/gi,                            'نفرتيتي'],
  [/\bCleopatra\b/gi,                            'كليوباترا'],
  [/\bAkhenaten\b/gi,                            'أخناتون'],
  [/\bSesostris\b/gi,                            'سيسوستريس'],
  [/\bMenkaure\b/gi,                             'منقرع'],
  [/\bKhufu\b/gi,                                'خوفو'],
  [/\bKhofo\b/gi,                                'خوفو'],
  [/\bTaharqa\b/gi,                              'طهارقا'],
  [/\bHoremheb\b/gi,                             'حور محب'],
  [/\bDjoser\b/gi,                               'زوسر'],
  [/\bPepi\b/gi,                                 'بيبي'],
  [/\bAmenemhat\b/gi,                            'أمنمحات'],
  [/\bCairo\b/gi,                                'القاهرة'],
  [/\bAlexandria\b/gi,                           'الإسكندرية'],
  [/\bAswan\b/gi,                                'أسوان'],
  [/\bLuxor\b/gi,                                'الأقصر'],
  [/\bKarnak\b/gi,                               'الكرنك'],
  [/\bMisr\b/gi,                                 'مصر'],
  [/\bEgypt\b/gi,                                'مصر'],
  [/\bEgyptian\b/gi,                             'مصري'],
  [/\bSinai\b/gi,                                'سيناء'],
  [/\bGiza\b/gi,                                 'الجيزة'],
  [/\bAsyut\b/gi,                                'أسيوط'],
  [/\bZagazig\b/gi,                              'الزقازيق'],
  [/\bHelwan\b/gi,                               'حلوان'],
  [/\bHellwan\b/gi,                              'حلوان'],
  [/\bAlamein\b/gi,                              'العلمين'],
  [/\bAlamain\b/gi,                              'العلمين'],
  [/\bNile\b/gi,                                 'النيل'],
  [/\bDelta\b/gi,                                'الدلتا'],
  [/\bKhartoum\b/gi,                             'الخرطوم'],
  [/\bTripoli\b/gi,                              'طرابلس'],
  [/\bTunis\b/gi,                                'تونس'],
  [/\bAlgiers\b/gi,                              'الجزائر'],
  [/\bDoha\b/gi,                                 'الدوحة'],
  [/\bDubai\b/gi,                                'دبي'],
  [/\bSharjah\b/gi,                              'الشارقة'],
  [/Abu Dhabi/gi,                                'أبوظبي'],
  [/\bSharjah\b/gi,                              'الشارقة'],
  [/\bKuwait\b/gi,                               'الكويت'],
  [/\bLondon\b/gi,                               'لندن'],
  [/\bParis\b/gi,                                'باريس'],
  [/\bBerlin\b/gi,                               'برلين'],
  [/\bBirmingham\b/gi,                           'برمنجهام'],
  [/\bJerusalem\b/gi,                            'القدس'],
  [/\bMombasa\b/gi,                              'مومباسا'],
  [/\bAnniversary\b/gi,                          'ذكرى'],
  [/\bIndependence\b/gi,                         'الاستقلال'],
  [/\bRevolution\b/gi,                           'الثورة'],
  [/\bLiberation\b/gi,                           'التحرير'],
  [/\bJubilee\b/gi,                              'اليوبيل'],
  [/\bCentennial\b/gi,                           'المئوية'],
  [/\bMillennium\b/gi,                           'الألفية'],
  [/\bCoronation\b/gi,                           'التتويج'],
  [/\bEnthronement\b/gi,                         'الاعتلاء'],
  [/\bAccession\b/gi,                            'الاعتلاء'],
  [/\bInauguration\b/gi,                         'الافتتاح'],
  [/\bReopening\b/gi,                            'إعادة الافتتاح'],
  [/\bNationalization\b/gi,                      'التأميم'],
  [/\bRefloating\b/gi,                           'إعادة التعويم'],
  [/\bEvacuation\b/gi,                           'الجلاء'],
  [/\bStatehood\b/gi,                            'الاستقلال'],
  [/\bUnification\b/gi,                          'التوحيد'],
  [/\bReturn\b/gi,                               'العودة'],
  [/\bBirthday\b/gi,                             'عيد الميلاد'],
  [/\bBirth\b/gi,                                'ميلاد'],
  [/\bDeath\b/gi,                                'وفاة'],
  [/\bMarriage\b/gi,                             'الزواج'],
  [/\bWedding\b/gi,                              'الزفاف'],
  [/\bReign\b/gi,                                'عهد'],
  [/\bGolden\b/gi,                               'الذهبي'],
  [/\bDiamond\b/gi,                              'الماسي'],
  [/\bSilver\b/gi,                               'الفضي'],
  [/\bEnthronement\b/gi,                         'الاعتلاء'],
  [/\bOlympics\b/gi,                             'الأولمبياد'],
  [/\bOlympic\b/gi,                              'أولمبي'],
  [/\bGames\b/gi,                                'الألعاب'],
  [/\bChampionship\b/gi,                         'البطولة'],
  [/\bChampionships\b/gi,                        'بطولات'],
  [/\bFIFA\b/gi,                                 'الفيفا'],
  [/\bFootball\b/gi,                             'كرة القدم'],
  [/\bSoccer\b/gi,                               'كرة القدم'],
  [/\bWrestling\b/gi,                            'المصارعة'],
  [/\bHandball\b/gi,                             'كرة اليد'],
  [/\bHockey\b/gi,                               'الهوكي'],
  [/\bSwimming\b/gi,                             'السباحة'],
  [/\bArchery\b/gi,                              'الرماية'],
  [/\bFencing\b/gi,                              'المبارزة'],
  [/\bTennis\b/gi,                               'التنس'],
  [/\bCycling\b/gi,                              'الدراجات'],
  [/\bKarate\b/gi,                               'الكاراتيه'],
  [/\bGymnastics\b/gi,                           'الجمباز'],
  [/\bAfrican\b/gi,                              'الأفريقي'],
  [/\bAsian\b/gi,                                'الآسيوي'],
  [/\bArab\b/gi,                                 'العربي'],
  [/\bWorld\b/gi,                                'العالمي'],
  [/\bCup\b/gi,                                  'الكأس'],
  [/\bStadium\b/gi,                              'الاستاد'],
  [/\bYouth\b/gi,                                'الشباب'],
  [/\bSports\b/gi,                               'الرياضة'],
  [/\bSporting\b/gi,                             'الرياضي'],
  [/\bUniversity\b/gi,                           'جامعة'],
  [/\bSchool\b/gi,                               'مدرسة'],
  [/\bCollege\b/gi,                              'كلية'],
  [/\bFaculty\b/gi,                              'كلية'],
  [/\bInstitute\b/gi,                            'معهد'],
  [/\bAcademy\b/gi,                              'أكاديمية'],
  [/\bMuseum\b/gi,                               'متحف'],
  [/\bLibrary\b/gi,                              'مكتبة'],
  [/\bBank\b/gi,                                 'بنك'],
  [/\bParliament\b/gi,                           'البرلمان'],
  [/\bRepublic\b/gi,                             'جمهورية'],
  [/\bKingdom\b/gi,                              'مملكة'],
  [/\bSultanate\b/gi,                            'سلطنة'],
  [/\bEmirate\b/gi,                              'إمارة'],
  [/\bNational\b/gi,                             'الوطني'],
  [/\bCentral\b/gi,                              'المركزي'],
  [/\bGeneral\b/gi,                              'العام'],
  [/\bMinistry\b/gi,                             'وزارة'],
  [/\bAuthority\b/gi,                            'هيئة'],
  [/\bCouncil\b/gi,                              'مجلس'],
  [/\bAssembly\b/gi,                             'مجلس'],
  [/\bCongress\b/gi,                             'مؤتمر'],
  [/\bConference\b/gi,                           'مؤتمر'],
  [/\bSummit\b/gi,                               'قمة'],
  [/\bForum\b/gi,                                'منتدى'],
  [/\bInternational\b/gi,                        'دولي'],
  [/\bOrganization\b/gi,                         'منظمة'],
  [/\bFederation\b/gi,                           'اتحاد'],
  [/\bUnion\b/gi,                                'اتحاد'],
  [/\bLeague\b/gi,                               'جامعة'],
  [/\bSociety\b/gi,                              'جمعية'],
  [/\bCompany\b/gi,                              'شركة'],
  [/\bCorporation\b/gi,                          'مؤسسة'],
  [/\bFoundation\b/gi,                           'مؤسسة'],
  [/\bChamber\b/gi,                              'غرفة'],
  [/\bIndustry\b/gi,                             'صناعة'],
  [/\bCommerce\b/gi,                             'تجارة'],
  [/\bAgriculture\b/gi,                          'الزراعة'],
  [/\bEducation\b/gi,                            'التعليم'],
  [/\bScience\b/gi,                              'العلوم'],
  [/\bHealth\b/gi,                               'الصحة'],
  [/\bCulture\b/gi,                              'الثقافة'],
  [/\bTourism\b/gi,                              'السياحة'],
  [/\bEnergy\b/gi,                               'الطاقة'],
  [/\bNuclear\b/gi,                              'النووي'],
  [/\bPetroleum\b/gi,                            'البترول'],
  [/\bOil\b/gi,                                  'النفط'],
  [/\bGas\b/gi,                                  'الغاز'],
  [/\bMining\b/gi,                               'التعدين'],
  [/\bProduction\b/gi,                           'الإنتاج'],
  [/\bBroadcasting\b/gi,                         'الإذاعة'],
  [/\bTelevision\b/gi,                           'التلفزيون'],
  [/\bRadio\b/gi,                                'الراديو'],
  [/\bMedia\b/gi,                                'الإعلام'],
  [/\bPlanning\b/gi,                             'التخطيط'],
  [/\bDevelopment\b/gi,                          'التنمية'],
  [/\bResearch\b/gi,                             'البحث'],
  [/\bPopulation\b/gi,                           'السكان'],
  [/\bCensus\b/gi,                               'التعداد'],
  [/\bPolice\b/gi,                               'الشرطة'],
  [/\bMilitary\b/gi,                             'العسكري'],
  [/\bArmy\b/gi,                                 'الجيش'],
  [/\bForce\b/gi,                                'القوة'],
  [/\bAir\b/gi,                                  'الجوي'],
  [/\bDefence\b/gi,                              'الدفاع'],
  [/\bJustice\b/gi,                              'العدالة'],
  [/\bLaw\b/gi,                                  'القانون'],
  [/\bCourt\b/gi,                                'المحكمة'],
  [/\bProsecution\b/gi,                          'النيابة'],
  [/\bInsurance\b/gi,                            'التأمين'],
  [/\bFinance\b/gi,                              'المالية'],
  [/\bTreasury\b/gi,                             'الخزانة'],
  [/\bExport\b/gi,                               'التصدير'],
  [/\bTrade\b/gi,                                'التجارة'],
  [/\bLabor\b/gi,                                'العمل'],
  [/\bWomen\b/gi,                                'المرأة'],
  [/\bChild\b/gi,                                'الطفل'],
  [/\bChildren\b/gi,                             'الأطفال'],
  [/\bHuman\b/gi,                                'الإنسان'],
  [/\bRights\b/gi,                               'الحقوق'],
  [/\bPeace\b/gi,                                'السلام'],
  [/\bWar\b/gi,                                  'الحرب'],
  [/\bVictory\b/gi,                              'النصر'],
  [/\bMartyrs\b/gi,                              'الشهداء'],
  [/\bHeritage\b/gi,                             'التراث'],
  [/\bAntiquities\b/gi,                          'الآثار'],
  [/\bHistory\b/gi,                              'التاريخ'],
  [/\bMonument\b/gi,                             'النصب التذكاري'],
  [/\bTemple\b/gi,                               'المعبد'],
  [/\bMosque\b/gi,                               'المسجد'],
  [/\bPyramid\b/gi,                              'الهرم'],
  [/\bPharaohs\b/gi,                             'الفراعنة'],
  [/\bGateway\b/gi,                              'البوابة'],
  [/\bGate\b/gi,                                 'البوابة'],
  [/\bTower\b/gi,                                'البرج'],
  [/\bBridge\b/gi,                               'الجسر'],
  [/\bMetro\b/gi,                                'المترو'],
  [/\bSubway\b/gi,                               'المترو'],
  [/\bTunnel\b/gi,                               'النفق'],
  [/\bAirport\b/gi,                              'المطار'],
  [/\bCanal\b/gi,                                'القناة'],
  [/\bDam\b/gi,                                  'السد'],
  [/\bSolar\b/gi,                                'الشمسي'],
  [/\bStation\b/gi,                              'المحطة'],
  [/\bPlant\b/gi,                                'المحطة'],
  [/\bRoad\b/gi,                                 'الطريق'],
  [/\bCoinage\b/gi,                              'العملة'],
  [/\bCurrency\b/gi,                             'العملة'],
  [/\bStandard\b/gi,                             'معيار'],
  [/\bPattern\b/gi,                              'نموذج'],
  [/\bMint\b/gi,                                 'دار الضرب'],
  [/\bIssue\b/gi,                                'إصدار'],
  [/\bDecade\b/gi,                               'عقد'],
  [/\bCentury\b/gi,                              'قرن'],
  [/\bAncient\b/gi,                              'قديم'],
  [/\bModern\b/gi,                               'حديث'],
  [/\bNew\b/gi,                                  'جديد'],
  [/\bGreat\b/gi,                                'عظيم'],
  [/\bKing\b/gi,                                 'ملك'],
  [/\bQueen\b/gi,                                'ملكة'],
  [/\bPrince\b/gi,                               'أمير'],
  [/\bPrincess\b/gi,                             'أميرة'],
  [/\bSheikh\b/gi,                               'شيخ'],
  [/\bPresident\b/gi,                            'رئيس'],
  [/\bLeader\b/gi,                               'قائد'],
  [/\bMother\b/gi,                               'الأم'],
  [/\bFamily\b/gi,                               'الأسرة'],
  [/\bHoly\b/gi,                                 'المقدس'],
  [/\bSacred\b/gi,                               'المقدس'],
  [/\bProphet\b/gi,                              'النبي'],
  [/\bGod\b/gi,                                  'الله'],
  [/\bGazelle\b/gi,                              'الغزال'],
  [/\bOryx\b/gi,                                 'المها'],
  [/\bFalcon\b/gi,                               'الصقر'],
  [/\bEagle\b/gi,                                'النسر'],
  [/\bLeopard\b/gi,                              'الفهد'],
  [/\bSphinx\b/gi,                               'أبو الهول'],
  [/\bIbex\b/gi,                                 'الوعل'],
  [/\bTahr\b/gi,                                 'الوعل'],
  [/\bDolphin\b/gi,                              'الدلفين'],
  [/\bCaracal\b/gi,                              'القط البري'],
  [/\bTurtle\b/gi,                               'السلحفاة'],
  [/\bButterfly\b/gi,                            'الفراشة'],
  [/\bBird\b/gi,                                 'الطائر'],
  [/\bND\b/gi,                                   'غير مؤرخ'],
  [/\bnd\b/gi,                                   'غير مؤرخ'],
  [/\bYears\b/gi,                                'سنة'],
  [/\bYear\b/gi,                                 'سنة'],
  [/\byears\b/gi,                                'سنة'],
  [/\bAnniversary\b/gi,                          'ذكرى'],
  [/\bHijrah\b/gi,                               'الهجرة'],
  [/\bHijra\b/gi,                                'الهجرة'],
  [/\bibn\b/gi,                                  'بن'],
  [/\bbin\b/gi,                                  'بن'],
  [/\bben\b/gi,                                  'بن'],
  [/\bal\b/gi,                                   'آل'],
  [/\bibn\b/gi,                                  'بن'],
  [/\bof\b/gi,                                   'من'],
  [/\bfor\b/gi,                                  'لـ'],
  [/\band\b/gi,                                  'و'],
  [/\bthe\b/gi,                                  'الـ'],
];

const ROMAN_END: [RegExp, string][] = [
  [/ VIII(?=$|\s)/gi, ' الثامن'],
  [/ VII(?=$|\s)/gi,  ' السابع'],
  [/ VI(?=$|\s)/gi,   ' السادس'],
  [/ IV(?=$|\s)/gi,   ' الرابع'],
  [/ IX(?=$|\s)/gi,   ' التاسع'],
  [/ III(?=$|\s)/gi,  ' الثالث'],
  [/ II(?=$|\s)/gi,   ' الثاني'],
  [/ I(?=$|\s)/gi,    ' الأول'],
  [/ V(?=$|\s)/gi,    ' الخامس'],
  [/ X(?=$|\s)/gi,    ' العاشر'],
];

function translateCoinName(name: string): string {
  let s = name;
  for (const [re, ar] of PHRASE_MAP) s = s.replace(re, ar);
  for (const [re, ar] of ROMAN_END)  s = s.replace(re, ar);
  return s.trim();
}

export const RARITY_AR: Record<string, string> = {
  Common: 'شائع', Uncommon: 'غير شائع', Scarce: 'نادر نسبياً', Rare: 'نادر',
};




export const DISC_GRADIENTS: Record<string, string> = {
  Gold:          'radial-gradient(circle at 36% 36%, #F7E08A, #C9A84C, #8B6D2E)',
  Silver:        'radial-gradient(circle at 36% 36%, #F2F2F2, #C8C8C8, #888)',
  Copper:        'radial-gradient(circle at 36% 36%, #ECA882, #C1714A, #7A3A1A)',
  Bronze:        'radial-gradient(circle at 36% 36%, #D4A96A, #A0714A, #603A18)',
  'Cupro-Nickel':'radial-gradient(circle at 36% 36%, #D8DDE6, #9AA4B2, #5A6472)',
  Nickel:        'radial-gradient(circle at 36% 36%, #D8DDE6, #9AA4B2, #5A6472)',
  Bimetallic:    'conic-gradient(from 0deg, #F7E08A, #C9A84C, #C8C8C8, #888, #F7E08A)',
  Aluminium:     'radial-gradient(circle at 36% 36%, #E8ECF2, #B0BAC8, #708090)',
  Brass:         'radial-gradient(circle at 36% 36%, #F0D870, #C8A838, #785A10)',
  Billon:        'radial-gradient(circle at 36% 36%, #D8C898, #A89868, #687040)',
  Steel:         'radial-gradient(circle at 36% 36%, #D0D4DA, #9AA0AA, #606878)',
  Other:         'radial-gradient(circle at 36% 36%, #F0E8D4, #D8C8A0, #A89060)',
};

export const METAL_BADGE_CLASSES: Record<string, string> = {
  Gold:          'bg-yellow-300 text-yellow-900',
  Silver:        'bg-gray-200 text-gray-800',
  Copper:        'bg-orange-300 text-orange-900',
  Bronze:        'bg-amber-400 text-amber-900',
  'Cupro-Nickel':'bg-slate-300 text-slate-800',
  Nickel:        'bg-slate-300 text-slate-800',
  Bimetallic:    'bg-gradient-to-r from-yellow-300 to-gray-300 text-gray-800',
  Aluminium:     'bg-slate-200 text-slate-700',
  Brass:         'bg-yellow-400 text-yellow-900',
  Billon:        'bg-stone-300 text-stone-800',
  Steel:         'bg-gray-300 text-gray-700',
  Other:         'bg-stone-200 text-stone-700',
};

export const COUNTRY_FLAGS: Record<string, string> = {
  EG: '🇪🇬', SA: '🇸🇦', AE: '🇦🇪', QA: '🇶🇦', QD: '🇶🇦',
  IQ: '🇮🇶', JO: '🇯🇴', LB: '🇱🇧', LY: '🇱🇾', MA: '🇲🇦',
  OM: '🇴🇲', PS: '🇵🇸', SD: '🇸🇩', SY: '🇸🇾', DZ: '🇩🇿',
  TN: '🇹🇳', YE: '🇾🇪', KW: '🇰🇼', MR: '🇲🇷',
};

export const COUNTRIES: { cc: string; co: string; co_ar: string }[] = [
  { cc: 'EG', co: 'Egypt',        co_ar: 'مصر' },
  { cc: 'MA', co: 'Morocco',      co_ar: 'المغرب' },
  { cc: 'SA', co: 'Saudi Arabia', co_ar: 'المملكة العربية السعودية' },
  { cc: 'AE', co: 'UAE',          co_ar: 'الإمارات' },
  { cc: 'IQ', co: 'Iraq',         co_ar: 'العراق' },
  { cc: 'OM', co: 'Oman',         co_ar: 'عُمان' },
  { cc: 'SD', co: 'Sudan',        co_ar: 'السودان' },
  { cc: 'LY', co: 'Libya',        co_ar: 'ليبيا' },
  { cc: 'SY', co: 'Syria',        co_ar: 'سوريا' },
  { cc: 'DZ', co: 'Algeria',      co_ar: 'الجزائر' },
  { cc: 'JO', co: 'Jordan',       co_ar: 'الأردن' },
  { cc: 'LB', co: 'Lebanon',      co_ar: 'لبنان' },
  { cc: 'TN', co: 'Tunisia',      co_ar: 'تونس' },
  { cc: 'YE', co: 'Yemen',        co_ar: 'اليمن' },
  { cc: 'QA', co: 'Qatar',        co_ar: 'قطر' },
  { cc: 'KW', co: 'Kuwait',       co_ar: 'الكويت' },
  { cc: 'PS', co: 'Palestine',    co_ar: 'فلسطين' },
  { cc: 'MR', co: 'Mauritania',   co_ar: 'موريتانيا' },
  { cc: 'QD', co: 'Qatar & Dubai',co_ar: 'قطر ودبي' },
];

export function getDiscGradient(metal: string): string {
  return DISC_GRADIENTS[metal] ?? DISC_GRADIENTS.Other;
}

export function getMetalSymbol(metal: string): string {
  const map: Record<string, string> = {
    Gold: 'ذ', Silver: 'ف', Bronze: 'ن', Copper: 'ن',
  };
  return map[metal] ?? 'ع';
}

export function formatMintage(mint: string, locale: string = 'ar'): string {
  if (!mint) return '';
  const n = parseInt(mint, 10);
  if (isNaN(n)) return mint;
  return n.toLocaleString(locale === 'ar' ? 'ar-EG' : 'en-US');
}

export function isValidImageUrl(url: string): boolean {
  return Boolean(url && url.startsWith('http') && !url.includes('no-obve') && !url.includes('no-reve'));
}

export function getCoinName(coin: Coin, locale: string): string {
  if (locale !== 'ar') return coin.name;
  const base = (coin.nar && coin.nar.trim()) ? coin.nar : coin.name;
  return translateCoinName(base);
}

export function getCoinYear(coin: Coin, locale: string): string {
  const ce = coin.yce ? `${coin.yce}${locale === 'ar' ? ' م' : ' CE'}` : '';
  const ah = coin.yah ? `(${coin.yah}${locale === 'ar' ? ' هـ' : ' AH'})` : '';
  return [ce, ah].filter(Boolean).join(' ');
}
